SET SCHEMA YELP;

DROP TYPE PAL_NBCTRAIN_TRAININGSET_T;
DROP TYPE PAL_CONTROL_T;
DROP TYPE PAL_NBC_MODEL_T;
DROP TABLE PAL_NBCTRAIN_PDATA_TBL;
DROP TABLE PAL_NBCTRAIN_TRAININGSET_TBL;
DROP TABLE #PAL_CONTROL_TBL;
DROP TABLE NBC_PAL_NBC_MODEL_TBL;

CREATE TYPE PAL_NBCTRAIN_TRAININGSET_T AS TABLE(
	"SP" INTEGER,
	"WP" INTEGER,
	"WN" INTEGER,
	"SN" INTEGER,
	"STARS" INTEGER
);

	
CREATE TYPE PAL_CONTROL_T AS TABLE( 
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);


CREATE TYPE PAL_NBC_MODEL_T AS TABLE(
	"ID" INTEGER,
	"JSONSTRING" VARCHAR(5000)
);


CREATE COLUMN TABLE PAL_NBCTRAIN_PDATA_TBL(
	"POSITION" INTEGER,
	"SCHEMA_NAME" VARCHAR(100),
	"TYPE_NAME" VARCHAR(100),
	"PARAMETER_TYPE" VARCHAR(100)
);
INSERT INTO PAL_NBCTRAIN_PDATA_TBL VALUES (1, 'YELP', 'PAL_NBCTRAIN_TRAININGSET_T', 'IN'); 
INSERT INTO PAL_NBCTRAIN_PDATA_TBL VALUES (2, 'YELP', 'PAL_CONTROL_T', 'IN'); 
INSERT INTO PAL_NBCTRAIN_PDATA_TBL VALUES (3, 'YELP', 'PAL_NBC_MODEL_T', 'OUT'); 

CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_DROP('YELP', 'PAL_NBCTRAIN_PROC');

CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'NBCTRAIN', 'YELP', 'PAL_NBCTRAIN_PROC', PAL_NBCTRAIN_PDATA_TBL);



CREATE COLUMN TABLE PAL_NBCTRAIN_TRAININGSET_TBL LIKE PAL_NBCTRAIN_TRAININGSET_T;

INSERT INTO PAL_NBCTRAIN_TRAININGSET_TBL( SP, WP, WN,SN,STARS)
SELECT   SP, WP, WN, SN, STARS FROM TRAINING_DATA;


CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL (
	"NAME" VARCHAR (100),
	"INTARGS" INTEGER,
	"DOUBLEARGS" DOUBLE,
	"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER',2,null,null); 
INSERT INTO #PAL_CONTROL_TBL VALUES ('IS_SPLIT_MODEL',0,null,null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('LAPLACE', null,1.0,null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MODEL_FORMAT', 1,null,null);


CREATE COLUMN TABLE NBC_PAL_NBC_MODEL_TBL LIKE PAL_NBC_MODEL_T;

CALL "YELP".PAL_NBCTRAIN_PROC(PAL_NBCTRAIN_TRAININGSET_TBL, "#PAL_CONTROL_TBL", NBC_PAL_NBC_MODEL_TBL) with overview;


SELECT * FROM NBC_PAL_NBC_MODEL_TBL;